apiVersion: v1
kind: Namespace
metadata:
  name: logs-generator-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logs-generator
  namespace: logs-generator-app
  labels:
    app: logs
    version: beta
spec:
  replicas: 3
  selector:
    matchLabels:
      app: logs
  template:
    metadata:
      labels:
        app: logs
        version: beta
    spec:
      containers:
      - name: logs-generator
        image: wacken/logs-generator:beta-2