apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flux-metrics
  labels:
    prometheus: active
    app: flux-metrics
spec:
  endpoints:
  - port: metrics
    path: '/metrics'
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: flux-metrics
      prometheus: active